name: Context testing

on: push

jobs:

  inits-context:
    runs-on: ubuntu-latest

    steps:
      - name: init context
        run: echo "context running on ${{github.ref}}"

  dumb-context:
    if: github.ref == 'refs/heads/main'
    needs: inits-context
    runs-on: ubuntu-latest
    steps:

      - name: Dumb git context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dumb job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dumb steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dumb runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
