name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout demo
      uses: actions/checkout@v4
    
    - name: Welcome message
      run: |
        echo "My first github actions"
        ls
        cat README.md

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y
    
    - name: Generate ASCII Chart
      run: cowsay -f dog "Hi Benzi. Love you!" >> dog.txt

    - name: Test file exits
      run: grep -i "dog" dog.txt
    
    - name: Read file
      run: cat dog.txt
    
    - name: List files
      run: ls -ltra


